name: Infrastructure Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    uses: FA9-lab/platform-workflows/.github/workflows/terraform-plan.yml@feature/deployment-repo-plan
    with:
      deployment-name: "orders-eastus-a7k29q-CHG123456"
      working-directory: "."
    secrets: inherit
